<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0RzxUmo\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0RzxUmo/Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0RzxUmo.legacy');

    return;
}

if (!\class_exists(Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false)) {
    \class_alias(\Container0RzxUmo\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false);
}

return new \Container0RzxUmo\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer([
    'container.build_hash' => '0RzxUmo',
    'container.build_id' => 'd94e78e8',
    'container.build_time' => 1675922974,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0RzxUmo');
