<?php

namespace Container2te7EaN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigDataObjectControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Bundle\DataImporterBundle\Controller\ConfigDataObjectController' shared autowired service.
     *
     * @return \Pimcore\Bundle\DataImporterBundle\Controller\ConfigDataObjectController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/DoubleAuthenticationControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Controller/ConfigDataObjectController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Helper/TemporaryFileHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Preview/PreviewService.php';

        $container->services['Pimcore\\Bundle\\DataImporterBundle\\Controller\\ConfigDataObjectController'] = $instance = new \Pimcore\Bundle\DataImporterBundle\Controller\ConfigDataObjectController(new \Pimcore\Bundle\DataImporterBundle\Preview\PreviewService(($container->privates['pimcore.dataImporter.preview.storage'] ?? $container->load('getPimcore_DataImporter_Preview_StorageService'))));

        $instance->setContainer(($container->privates['.service_locator.oafe0zm'] ?? $container->load('get_ServiceLocator_Oafe0zmService'))->withContext('Pimcore\\Bundle\\DataImporterBundle\\Controller\\ConfigDataObjectController', $container));

        return $instance;
    }
}
