pimcore:
    workflows:
        workflow:
            label: "Product Workflow"
            type: "state_machine"
            supports:
                - 'Pimcore\Model\DataObject\Grocery'
            places:
                base:
                    label: "Base Attributes"
                    color: "#377ea9"
                    permissions:
                        - objectLayout: 1
                
                features:
                    label: "features"
                    title: "Updating content step"
                    color: "#d9ef36"
                    permissions:
                        - objectLayout: 2

                set manufacturer and seller:
                    label: "Update Manufacturer + Seller"
                    title: "Update Manufacturer + Seller"
                    color: "#d9ef36"
                    permissions:
                        - objectLayout: 4

                media:
                    label: "media"
                    title: "Image gallery"
                    color: "#d9ef36"
                    permissions:
                        - objectLayout: 3

                content_prepared:
                    label: "Content Prepared"
                    title: "Content ready to publish"
                    color: "#28a013"

                accepted:
                    label: "Accepted product"
                    color: "#28a013"

                reject:
                    label: "Reject product"
                    color: "#28a013"
                Modify:
                    label: "Modify product"
                    color: "#28a013"

            transitions:
                add_base_attributes:
                    from: base
                    to: features
                    guard: "is_fully_authenticated() and (is_granted('ROLE_DATAENTRY') or is_granted('ROLE_PIMCORE_ADMIN'))"
                    options:
                        label: "set features"
                        notes:
                            commentEnabled: true
                            commentRequired: true

                add_features:
                    from: media
                    to: set manufacturer and seller
                    guard: "is_fully_authenticated() and (is_granted('ROLE_DATAENTRY')  or is_granted('ROLE_PIMCORE_ADMIN'))"
                    options:
                        label: "set manufacturer and seller"
                        notes:
                            commentEnabled: true
                            commentRequired: false

                add_mf_sl:
                    from: features
                    to: media
                    guard: "is_fully_authenticated() and (is_granted('ROLE_DATAENTRY')  or is_granted('ROLE_PIMCORE_ADMIN'))"
                    options:
                        label: "set media"
                        notes:
                            commentEnabled: true
                            commentRequired: false
                
                add_media:
                    from: set manufacturer and seller
                    to: content_prepared
                    guard: "is_fully_authenticated() and (is_granted('ROLE_DATAENTRY') or is_granted('ROLE_PIMCORE_ADMIN'))"
                    options:
                        label: "prepare"
                        # notes:
                        #     commentEnabled: true
                        #     commentRequired: false

                accept_transition:
                    from: content_prepared
                    to: accepted
                    guard: "is_fully_authenticated() and (is_granted('ROLE_REVIEWER')  or is_granted('ROLE_PIMCORE_ADMIN'))"
                    options:
                        label: "accept"
                        notes:
                            commentEnabled: true
                            commentRequired: false

                reject_transition:
                    from: content_prepared
                    to: reject
                    guard: "is_fully_authenticated() and (is_granted('ROLE_REVIEWER') or is_granted('ROLE_PIMCORE_ADMIN'))"
                    options:
                        label: "reject"
                        notes:
                            commentEnabled: true
                            commentRequired: false
                Modify_transition:
                    from: reject
                    to: base
                    guard: "is_fully_authenticated() and (is_granted('ROLE_DATAENTRY') or is_granted('ROLE_PIMCORE_ADMIN'))"
                    options:
                        label: "Modify"
                        notes:
                            commentEnabled: true
                            commentRequired: false
