<?php

namespace ContainerYoCZ7ow;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflow_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'workflow.registry' shared autowired service.
     *
     * @return \Symfony\Component\Workflow\Registry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Registry.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/SupportStrategy/WorkflowSupportStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/SupportStrategy/InstanceOfSupportStrategy.php';

        $container->privates['workflow.registry'] = $instance = new \Symfony\Component\Workflow\Registry();

        $instance->addWorkflow(($container->services['state_machine.workflow'] ?? $container->load('getStateMachine_WorkflowService')), new \Symfony\Component\Workflow\SupportStrategy\InstanceOfSupportStrategy('Pimcore\\Model\\DataObject\\Grocery'));

        return $instance;
    }
}
