<?php

namespace ContainerYoCZ7ow;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflow_Security_ExpressionLanguageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'workflow.security.expression_language' shared autowired service.
     *
     * @return \Symfony\Component\Workflow\EventListener\ExpressionLanguage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/EventListener/ExpressionLanguage.php';

        return $container->privates['workflow.security.expression_language'] = new \Symfony\Component\Workflow\EventListener\ExpressionLanguage(($container->services['cache.app'] ?? $container->getCache_AppService()));
    }
}
