<?php

namespace ContainerPzx5FUJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebsite_OptionsproviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Website.optionsprovider' shared autowired service.
     *
     * @return \App\DynamicDropdown\BiscuitFlavour
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/DynamicOptionsProvider/MultiSelectOptionsProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/DynamicOptionsProvider/SelectOptionsProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DynamicDropdown/BiscuitFlavour.php';

        return $container->services['Website.optionsprovider'] = new \App\DynamicDropdown\BiscuitFlavour();
    }
}
