<?php

namespace ContainerBB9CMY5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassificationStoreDataTypeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\DataImporterBundle\Mapping\Type\ClassificationStoreDataTypeService' shared autowired service.
     *
     * @return \Pimcore\Bundle\DataImporterBundle\Mapping\Type\ClassificationStoreDataTypeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Mapping/Type/ClassificationStoreDataTypeService.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Mapping/Type/TransformationDataTypeService.php';

        return $container->privates['Pimcore\\Bundle\\DataImporterBundle\\Mapping\\Type\\ClassificationStoreDataTypeService'] = new \Pimcore\Bundle\DataImporterBundle\Mapping\Type\ClassificationStoreDataTypeService(($container->privates['Pimcore\\Bundle\\DataImporterBundle\\Mapping\\Type\\TransformationDataTypeService'] ?? ($container->privates['Pimcore\\Bundle\\DataImporterBundle\\Mapping\\Type\\TransformationDataTypeService'] = new \Pimcore\Bundle\DataImporterBundle\Mapping\Type\TransformationDataTypeService())));
    }
}
