<?php

namespace ContainerBB9CMY5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataImporterHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\DataImporterBundle\Messenger\DataImporterHandler' shared autowired service.
     *
     * @return \Pimcore\Bundle\DataImporterBundle\Messenger\DataImporterHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Messenger/DataImporterHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Queue/QueueService.php';

        $a = ($container->privates['Pimcore\\Bundle\\DataImporterBundle\\Processing\\ImportProcessingService'] ?? $container->load('getImportProcessingServiceService'));

        if (isset($container->privates['Pimcore\\Bundle\\DataImporterBundle\\Messenger\\DataImporterHandler'])) {
            return $container->privates['Pimcore\\Bundle\\DataImporterBundle\\Messenger\\DataImporterHandler'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->getMessenger_DefaultBusService());

        if (isset($container->privates['Pimcore\\Bundle\\DataImporterBundle\\Messenger\\DataImporterHandler'])) {
            return $container->privates['Pimcore\\Bundle\\DataImporterBundle\\Messenger\\DataImporterHandler'];
        }

        return $container->privates['Pimcore\\Bundle\\DataImporterBundle\\Messenger\\DataImporterHandler'] = new \Pimcore\Bundle\DataImporterBundle\Messenger\DataImporterHandler(($container->privates['Pimcore\\Bundle\\DataImporterBundle\\Queue\\QueueService'] ?? ($container->privates['Pimcore\\Bundle\\DataImporterBundle\\Queue\\QueueService'] = new \Pimcore\Bundle\DataImporterBundle\Queue\QueueService())), $a, $b, 1800, 200, 3);
    }
}
