<?php

namespace ContainerBB9CMY5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExecutorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Maintenance\Executor' shared autowired service.
     *
     * @return \Pimcore\Maintenance\Executor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/ExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Executor.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/TaskInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/ScheduledTasksTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/LogMailMaintenanceTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/LogCleanupTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/LogErrorCleanupTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/LogArchiveTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/CleanupBrickTablesTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/CleanupClassificationstoreTablesTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/VersionsCleanupTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/VersionsCleanupStackTraceDbTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/RedirectCleanupTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/DbCleanupBrokenViewsTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/TmpStoreCleanupTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/HousekeepingTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/LowQualityImagePreviewTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/StaticPagesGenerationTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/FullTextIndexOptimizeTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Maintenance/RestartQueueWorkersTask.php';

        $a = ($container->services['Symfony\\Component\\Lock\\LockFactory'] ?? $container->getLockFactoryService());

        if (isset($container->privates['Pimcore\\Maintenance\\Executor'])) {
            return $container->privates['Pimcore\\Maintenance\\Executor'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->getMessenger_DefaultBusService());

        if (isset($container->privates['Pimcore\\Maintenance\\Executor'])) {
            return $container->privates['Pimcore\\Maintenance\\Executor'];
        }
        $c = ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService());

        $container->privates['Pimcore\\Maintenance\\Executor'] = $instance = new \Pimcore\Maintenance\Executor('maintenance.pid', $c, $a, $b);

        $d = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());
        $e = ($container->services['Pimcore\\Config'] ?? ($container->services['Pimcore\\Config'] = new \Pimcore\Config()));

        $instance->registerTask('scheduledtasks', new \Pimcore\Maintenance\Tasks\ScheduledTasksTask($c));
        $instance->registerTask('logmaintenance', new \Pimcore\Maintenance\Tasks\LogMailMaintenanceTask($d, $e));
        $instance->registerTask('cleanuplogfiles', new \Pimcore\Maintenance\Tasks\LogCleanupTask());
        $instance->registerTask('httperrorlog', new \Pimcore\Maintenance\Tasks\LogErrorCleanupTask($d));
        $instance->registerTask('archiveLogEntries', new \Pimcore\Maintenance\Tasks\LogArchiveTask($d, $e, $c));
        $instance->registerTask('cleanupBrickTables', new \Pimcore\Maintenance\Tasks\CleanupBrickTablesTask($c));
        $instance->registerTask('cleanupClassificationstoreTables', new \Pimcore\Maintenance\Tasks\CleanupClassificationstoreTablesTask($c));
        $instance->registerTask('cleanupFieldcollectionTables', new \Pimcore\Maintenance\Tasks\CleanupFieldcollectionTablesTask($c));
        $instance->registerTask('versioncleanup', new \Pimcore\Maintenance\Tasks\VersionsCleanupTask($c, $e));
        $instance->registerTask('VersionsCleanupStackTraceDb', new \Pimcore\Maintenance\Tasks\VersionsCleanupStackTraceDbTask($c));
        $instance->registerTask('redirectcleanup', new \Pimcore\Maintenance\Tasks\RedirectCleanupTask($c));
        $instance->registerTask('cleanupbrokenviews', new \Pimcore\Maintenance\Tasks\DbCleanupBrokenViewsTask($d, $c));
        $instance->registerTask('tmpstorecleanup', new \Pimcore\Maintenance\Tasks\TmpStoreCleanupTask($d));
        $instance->registerTask('housekeeping', new \Pimcore\Maintenance\Tasks\HousekeepingTask(7776000, 1800));
        $instance->registerTask('low_quality_image_preview', new \Pimcore\Maintenance\Tasks\LowQualityImagePreviewTask($c, $a));
        $instance->registerTask('documents_static_page_generate', new \Pimcore\Maintenance\Tasks\StaticPagesGenerationTask(($container->services['Pimcore\\Document\\StaticPageGenerator'] ?? $container->getStaticPageGeneratorService()), $c));
        $instance->registerTask('optimize_fulltext_indexes', new \Pimcore\Maintenance\Tasks\FullTextIndexOptimizeTask($a));
        $instance->registerTask('data_importer.restart_queue_workers', new \Pimcore\Bundle\DataImporterBundle\Maintenance\RestartQueueWorkersTask(($container->privates['Pimcore\\Bundle\\DataImporterBundle\\Messenger\\DataImporterHandler'] ?? $container->load('getDataImporterHandlerService')), false));

        return $instance;
    }
}
