<?php

namespace ContainerBB9CMY5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResolverFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\DataImporterBundle\Resolver\ResolverFactory' shared autowired service.
     *
     * @return \Pimcore\Bundle\DataImporterBundle\Resolver\ResolverFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/ResolverFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Resolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Settings/SettingsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Load/LoadStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Load/AbstractLoad.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Load/IdStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Load/PathStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Load/AttributeStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Load/NotLoadStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Location/LocationStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Location/FindParentStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Location/FindOrCreateFolderStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Location/NoChangeStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Location/StaticPathStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Location/DoNotCreateStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Publish/PublishStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Publish/AlwaysPublishStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Publish/AttributeBasedStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Publish/NoChangePublishNewStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Publish/NoChangeUnpublishNewStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Factory/FactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Resolver/Factory/DataObjectFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Tool/DataObjectLoader.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->privates['Pimcore\\Bundle\\DataImporterBundle\\Resolver\\ResolverFactory'])) {
            return $container->privates['Pimcore\\Bundle\\DataImporterBundle\\Resolver\\ResolverFactory'];
        }
        $b = ($container->privates['Pimcore\\Bundle\\DataImporterBundle\\Tool\\DataObjectLoader'] ?? ($container->privates['Pimcore\\Bundle\\DataImporterBundle\\Tool\\DataObjectLoader'] = new \Pimcore\Bundle\DataImporterBundle\Tool\DataObjectLoader()));

        return $container->privates['Pimcore\\Bundle\\DataImporterBundle\\Resolver\\ResolverFactory'] = new \Pimcore\Bundle\DataImporterBundle\Resolver\ResolverFactory(new \Pimcore\Bundle\DataImporterBundle\Resolver\Resolver(), ['id' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Load\IdStrategy($a, $b), 'path' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Load\PathStrategy($a, $b), 'attribute' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Load\AttributeStrategy($a, $b), 'notLoad' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Load\NotLoadStrategy()], ['findParent' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Location\FindParentStrategy($b), 'findOrCreateFolder' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Location\FindOrCreateFolderStrategy($b), 'noChange' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Location\NoChangeStrategy(), 'staticPath' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Location\StaticPathStrategy(), 'doNotCreate' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Location\DoNotCreateStrategy()], ['alwaysPublish' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Publish\AlwaysPublishStrategy(), 'attributeBased' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Publish\AttributeBasedStrategy(), 'noChangePublishNew' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Publish\NoChangePublishNewStrategy(), 'noChangeUnpublishNew' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Publish\NoChangeUnpublishNewStrategy()], ['dataObject' => new \Pimcore\Bundle\DataImporterBundle\Resolver\Factory\DataObjectFactory(($container->services['pimcore.model.factory'] ?? $container->load('getPimcore_Model_FactoryService')))]);
    }
}
