<?php

namespace ContainerFQOrvfZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UaP0DWwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uaP0DWw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uaP0DWw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'configurationPreparationService' => ['privates', 'Pimcore\\Bundle\\DataImporterBundle\\Settings\\ConfigurationPreparationService', 'getConfigurationPreparationServiceService', true],
            'factory' => ['privates', 'Pimcore\\Bundle\\DataImporterBundle\\Mapping\\MappingConfigurationFactory', 'getMappingConfigurationFactoryService', true],
            'importProcessingService' => ['privates', 'Pimcore\\Bundle\\DataImporterBundle\\Processing\\ImportProcessingService', 'getImportProcessingServiceService', true],
            'interpreterFactory' => ['privates', 'Pimcore\\Bundle\\DataImporterBundle\\DataSource\\Interpreter\\InterpreterFactory', 'getInterpreterFactoryService', true],
        ], [
            'configurationPreparationService' => 'Pimcore\\Bundle\\DataImporterBundle\\Settings\\ConfigurationPreparationService',
            'factory' => 'Pimcore\\Bundle\\DataImporterBundle\\Mapping\\MappingConfigurationFactory',
            'importProcessingService' => 'Pimcore\\Bundle\\DataImporterBundle\\Processing\\ImportProcessingService',
            'interpreterFactory' => 'Pimcore\\Bundle\\DataImporterBundle\\DataSource\\Interpreter\\InterpreterFactory',
        ]);
    }
}
