<?php

namespace ContainerFQOrvfZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransformationDataTypeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\DataImporterBundle\Mapping\Type\TransformationDataTypeService' shared autowired service.
     *
     * @return \Pimcore\Bundle\DataImporterBundle\Mapping\Type\TransformationDataTypeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Mapping/Type/TransformationDataTypeService.php';

        return $container->privates['Pimcore\\Bundle\\DataImporterBundle\\Mapping\\Type\\TransformationDataTypeService'] = new \Pimcore\Bundle\DataImporterBundle\Mapping\Type\TransformationDataTypeService();
    }
}
