<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBB9CMY5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBB9CMY5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBB9CMY5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBB9CMY5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBB9CMY5\App_KernelDevDebugContainer([
    'container.build_hash' => 'BB9CMY5',
    'container.build_id' => 'd94e4f9d',
    'container.build_time' => 1676206765,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBB9CMY5');
