<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2te7EaN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2te7EaN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2te7EaN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2te7EaN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2te7EaN\App_KernelDevDebugContainer([
    'container.build_hash' => '2te7EaN',
    'container.build_id' => '4df1c1ee',
    'container.build_time' => 1675963656,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2te7EaN');
