<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFQOrvfZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFQOrvfZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFQOrvfZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFQOrvfZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFQOrvfZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'FQOrvfZ',
    'container.build_id' => 'e1bf34e1',
    'container.build_time' => 1676022019,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFQOrvfZ');
